<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZF5OvIw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZF5OvIw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZF5OvIw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZF5OvIw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZF5OvIw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZF5OvIw',
    'container.build_id' => '0f929a6a',
    'container.build_time' => 1566318841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZF5OvIw');
