<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerANxPGzs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerANxPGzs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerANxPGzs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerANxPGzs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerANxPGzs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ANxPGzs',
    'container.build_id' => 'b689a474',
    'container.build_time' => 1566477168,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerANxPGzs');
