<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhp8fqW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhp8fqW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYhp8fqW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYhp8fqW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYhp8fqW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Yhp8fqW',
    'container.build_id' => 'abd03e22',
    'container.build_time' => 1566309634,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhp8fqW');
